title: Knet Solutions - SDN Training - SDN Project Assistance
author:
  name: Suresh Kumar                      # Default author name
  email: 'knetsolutions2@gmail.com'                   # Default author email
  copyright: "Copyright 2018 Knet Solutions. All Rights Reserved."
contact:
  address:
    - line: "Pallikaranai"
    - line: "Chennai, TamilNadu"
    - line: "India"
    - line: "Whatsapp/Phone:  +91 9445042007"
othermenu:
  - text: "About"
    url: "about"
  - text: "Privacy Policy"
    url: "#"
  - text: "Contact"
    url: "contact"
quicklinks:
  - text: "Facebook Page"
    url : "https://www.facebook.com/sdntraining/"
  - text: "Youtube channel"
    url : "https://www.youtube.com/channel/UCTD6X9_oDqIYs_xpE7moFnQ"
  - text: "About"
    url: "base_url:about"
  - text: "SDN Tutorials"
    url: "base_url:sdn-tutorials"   
  - text: "Contact Us"
    url: "base_url:contact"          
taxonomies: [category,tag]                  # Arbitrary list of taxonomy types
blog:
  route: '/blog'                            # Route to blog
metadata:
    google-site-verification: "LH5pPzqtttwhMxUIH7ecXY5wT0S1A9cJdYri4WpcpNE"
    title: 'SDN Training & Project assistance'
    tag: 'SDN Training, SDN Projects, SDN Thesis, Openflow Projects, Mininet Projects'
    description: 'Best Online Software Defined Networking (SDN) Training center. Excellent SDN Course. Best Academic SDN Project center in Chennai. Final year Projects, CSE mini projects.' 
    keywords: 'SDN Projects, SDN IEEE Projects, SDN MTech Projects, SDN Thesis, SDN Training, Mininet Projects, Openflow projects, Online SDN Training, Opendaylight training, SDN Project center in chennai, SDN project center in Bangalore, SDN Project center in hyderabad,  SDN Project center in India'
summary:
  size: 300                                 # Maximum length of summary (characters)

header_options:
  arrows: 'true'                            # Create Next and previous button
  autoslide: 'false'                        # Auto slideshow mode
  autoslideHoverStop: 'false'               # Pause auto slideshow mode on mouseover
  interval: '500'                          # The interval between each slide (Interval in millisecond)
  loop: 'false'                             # Infinite slideshow             
  transition : zoom                         # Set the animation kind (fade/slide/page/zoom)
  itemsForSlide: '0'                        # Wrap each 'n' item
  touch: 'true'                             # Set a native slide for touch device
  swipe : 'true'                            # Enable swipe for touch device

footer:
    description: "KNet Solutions provides practical/hands-on training with Industry experts. The Instructor has 17 years of IT industry experience and  contributes(upstream) in Openstack and SDN Projects."
    contact_title: "Contact Info"
    links_title: "Quick Links"
    copyright_text: "Copyright 2018 Knet solutions. All Rights Reserved."


