home:
  alias: '/home'

pages:
  theme: deliver
  process:
    markdown: true
    twig: false
  markdown:
    extra: false  

metadata:
    refresh: 30
    generator: 'Grav'
    description: 'Training in Software Defined Networking, SDN, RYU, Opendaylight, Mininet, Openstack. Academic Projects assistance in SDN'
    keywords: 'SDN, Software Defined Networking, RYU, Opendaylight, ODL, Mininet, Openstack'
    author: 'Knet solutions'

cache:
  enabled: false
  check:
    method: file
  driver: auto
  prefix: 'g'

twig:
  cache: true
  debug: true
  auto_reload: true
  autoescape: false

assets:
  css_pipeline: false
  css_minify: true
  css_rewrite: true
  js_pipeline: false
  js_minify: true

debugger:
  enabled: false
  twig: true
  shutdown:
    close_connection: true
